services:
  - type: web
    name: flask-selenium-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y firefox-esr
      wget https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz
      tar -xvzf geckodriver-v0.32.0-linux64.tar.gz
      chmod +x geckodriver
      mv geckodriver /usr/local/bin/
    startCommand: gunicorn api.index:app
    envVars:
      - key: GECKODRIVER_PATH
        value: /usr/local/bin/geckodriver
